RaiseOnColon: implement without using guava, was causing issues with guava 18.0 (#4)
Was seeing this exception: `java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V`.

Changed the test to verify the metric name is in fact visible.